<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'terminator\\interfaces\\style' => '/../src/Terminator/Interfaces/Style.php',
                'terminator\\nostyle' => '/../src/Terminator/NoStyle.php',
                'terminator\\out' => '/../src/Terminator/Out.php',
                'terminator\\outtest' => '/src/OutTest.php',
                'terminator\\style' => '/../src/Terminator/Style.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
